### ISSUE TITLE
Deleted depth surfaces do not seem to be deleted in the project file.

### ISSUE THREAD

**Issue by bklappauf** [twdb/hydropick#88]
AFAICT all the machinery for deleting a surface from a surveyline depth dictionary seems to work and the surveyline save function is called but then when the line is reloaded all the surfaces are still there.   I believe the hdf5 save is just overwriting the entries that remain in the dictionary without removing the ones no longer there.

one alternative to removing them is to mark them as  'removed' via a flag.  they could then in principle be restored, but logic could be build in to not read these into the surveyline model when it is created for a session.

**Comment by toddjm** [comment]
This has been fixed by directly removing the node(s) in question from the h5 file(s). - see #140.
