### ISSUE TITLE
subsample exported data

### ISSUE THREAD

**Issue by wilsaj** [twdb/hydropick#95]
subsample to 1 value per n frequencies - this is the behavior of depthpic, and one value per trace is more data than is needed

**Comment by toddjm** [comment]
The particular case for Bachman line 15021912 happens to correspond to bad data in the SDI_Data directory - can you (Holly) please look at examples from another survey (such as White Rock) and see if the behavior is observed?

**Comment by toddjm** [comment]
Closing per #148
